# Generated by Django 4.0.4 on 2022-07-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_id_contact_sno_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
