# Generated by Django 4.0.4 on 2022-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sno',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
    ]
